# Generated by Django 5.1.4 on 2025-01-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=100)),
                ('fruit', models.CharField(max_length=100)),
                ('planet', models.CharField(max_length=100)),
            ],
        ),
    ]
