# Generated by Django 5.1.4 on 2025-01-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='fruit',
        ),
        migrations.RemoveField(
            model_name='item',
            name='planet',
        ),
    ]
